AY1920S1-CS2113-T13-3/main

src/main/java/command/PostponeCommand.java, src/main/java/parser/DateTimeExtractor.java, src/main/java/parser/Parser.java, src/main/java/task/Event.java, src/main/java/task/Task.java, src/main/java/task/TaskList.java
Updated parser to include parse "postpone" commands
Created new tasklist method to update date of tasks
Create new command class for Postpone
=> Added ability to postpone tasks schedule

src/main/java/command/AddCommand.java, src/main/java/command/FindCommand.java, src/main/java/command/PostponeCommand.java, src/main/java/command/ViewCommand.java, src/main/java/parser/DateTimeExtractor.java, src/main/java/parser/Parser.java, src/main/java/task/Deadline.java, src/main/java/task/Task.java, src/main/java/task/TaskList.java, src/main/java/task/Todo.java, src/test/java/AddCommandTest.java, src/test/java/TodoTest.java, src/test/java/ViewCommandTest.java
All functions are currently working and removed redundant issue fixes. Changed all nullDate references to the sample as LocalDateTime variable cannot be initialised with zeros eg. month has to be within 1-12
=> Added ViewCommand, Tests for certain tasks and commands and fixed nullDate issue.

src/main/java/command/SearchCommand.java, src/main/java/task/Deadline.java, src/main/java/task/Event.java, src/main/java/task/Task.java, src/main/java/task/TaskList.java, src/main/java/task/Todo.java, src/test/java/TodoTest.java
refactored atDate & fromDate into a common startDate
=> Refactor Task dates to startDate & endDate

src/main/java/command/EditCommand.java, src/main/java/parser/Parser.java, src/main/java/task/TaskList.java, src/test/java/EditCommandTest.java
Implemented function that allows users to edit their task descriptions.
=> B -EditDescription

config/checkstyle/checkstyle.xml, src/main/java/command/AddCommand.java, src/main/java/command/IgnoreCommand.java, src/main/java/parser/Parser.java, src/main/java/task/Deadline.java, src/main/java/task/Event.java, src/main/java/task/Task.java, src/main/java/task/TaskList.java, src/main/java/task/Todo.java, src/main/java/task/TodoWithDuration.java, src/main/java/task/TodoWithinPeriod.java, src/test/java/DeadlineTest.java, src/test/java/ParserTest.java, src/test/java/RemindCommandTest.java, src/test/java/TodoTest.java
Added support for tasks with fixed duration, to ignore reminders/deadlines
Refactored Parser code and added more test cases
=> B-FixedDurationTasks, isIgnorable feature & test cases/refactoring

src/main/java/command/EditCommand.java, src/main/java/command/IgnoreCommand.java, src/main/java/command/PriorityCommand.java, src/main/java/exception/DukeException.java, src/main/java/parser/Parser.java, src/main/java/task/Deadline.java, src/main/java/task/Event.java, src/main/java/task/Priority.java, src/main/java/task/Task.java, src/main/java/task/TaskList.java, src/main/java/task/Todo.java, src/main/java/task/TodoWithDuration.java, src/main/java/task/TodoWithinPeriod.java, src/test/java/DeadlineTest.java, src/test/java/TodoTest.java
=> B priority

src/main/java/Main.java, src/main/java/command/CommentCommand.java, src/main/java/command/SearchCommand.java, src/main/java/exception/DukeException.java, src/main/java/parser/Parser.java, src/main/java/task/Deadline.java, src/main/java/task/Event.java, src/main/java/task/Task.java, src/main/java/task/TaskList.java, src/main/java/task/Todo.java, src/main/java/task/TodoWithDuration.java, src/main/java/task/TodoWithinPeriod.java, src/test/java/CommentCommandTest.java, src/test/java/SearchCommandTest.java
=> ability to add/edit comments

src/main/java/command/PostponeCommand.java, src/main/java/parser/DeadlineParser.java, src/main/java/parser/ParserFactory.java, src/main/java/task/Deadline.java, src/main/java/task/Task.java, src/main/java/task/TaskList.java, src/main/java/task/TodoWithDuration.java, src/main/java/task/TodoWithinPeriod.java, src/test/java/DeadlineTest.java
Refactor postpone command and its parser case.
Updated to use localDateTime variables.
=> Refactor postpone command .

src/main/java/exception/DukeException.java, src/main/java/parser/CommentParser.java, src/main/java/parser/DeleteParser.java, src/main/java/parser/DoneParser.java, src/main/java/parser/EditParser.java, src/main/java/parser/IndexParser.java, src/main/java/parser/ParserFactory.java, src/main/java/parser/PriorityParser.java
Added and implement parser sub-classes for minor functionality.
Functionalities likely to be heavily changed left untouched
=> Refactor Parser subclasses

src/main/java/DialogBox.java, src/main/java/MainWindow.java, src/main/java/command/ViewCommand.java, src/main/java/task/TaskList.java, src/main/java/ui/Ui.java, src/main/resources/view/DialogBox.fxml, src/main/resources/view/MainWindow.fxml
the errors were regrading view schedule, todo tasks with dates
the gui is now a lot cleaner. finishing up the timeline now!
=> Cleaned up GUI code and fixed errors 

src/main/java/parser/CommentParser.java, src/main/java/parser/EditParser.java, src/main/java/parser/EventParser.java, src/main/java/parser/FindParser.java, src/main/java/parser/IgnoreParser.java, src/main/java/parser/IndexParser.java, src/main/java/parser/LocationParser.java, src/main/java/parser/ParserFactory.java, src/main/java/parser/PostponeParser.java, src/main/java/parser/PriorityParser.java, src/main/java/parser/SearchParser.java, src/main/java/parser/ViewParser.java
Refactor parser package completely.
=> Created more parser subclasses to adhere  OOP paradigm.

src/main/java/MainWindow.java, src/main/java/command/AddCommand.java, src/main/java/command/Command.java, src/main/java/command/CommentCommand.java, src/main/java/command/DeleteCommand.java, src/main/java/command/DoneCommand.java, src/main/java/command/EditCommand.java, src/main/java/command/ExitCommand.java, src/main/java/command/FindCommand.java, src/main/java/command/IgnoreCommand.java, src/main/java/command/ListCommand.java, src/main/java/command/LocationCommand.java, src/main/java/command/PostponeCommand.java, src/main/java/command/PriorityCommand.java, src/main/java/command/RemindCommand.java, src/main/java/command/SearchCommand.java, src/main/java/command/ViewCommand.java, src/main/java/parser/IndexParser.java, src/main/java/parser/ParserFactory.java, src/main/resources/view/DialogBox.fxml, src/main/resources/view/MainWindow.fxml
Updated GUI with some touch ups based on trial users. JavaDocs has been fixed.
=> Done with formatting all command JavaDocs

src/main/java/ErrorMessageBar.java, src/main/java/Main.java, src/main/java/command/ViewCommand.java, src/main/java/exception/DukeException.java, src/main/java/parser/IndexParser.java, src/main/java/parser/ParserFactory.java, src/main/java/parser/ViewParser.java, src/main/java/task/Todo.java, src/test/java/DeadlineTest.java
=> fixed issue with "Magic" Strings in exceptions

src/main/java/command/PostponeCommand.java, src/main/java/parser/DescriptionParser.java, src/main/java/parser/EventParser.java, src/main/java/parser/IndexParser.java, src/main/java/parser/Parser.java, src/main/java/parser/PostponeParser.java, src/main/java/parser/TodoParser.java, src/main/java/parser/TodoWithDurationParser.java, src/main/java/parser/TodoWithinPeriodParser.java
Minor changes to postpone,remove unnecessary checks.
Todo postpone will be implemented once our overhaul to TODO is completed.
=> Refactor PostponeCommand

.gitignore, src/main/java/exception/DukeException.java, src/main/java/exception/MyLogger.java, src/main/java/parser/CommentParser.java, src/main/java/parser/DeadlineParser.java, src/main/java/parser/EventParser.java, src/main/java/parser/IndexParser.java, src/main/java/parser/LocationParser.java, src/main/java/parser/Parser.java, src/main/java/parser/PostponeParser.java, src/main/java/parser/PriorityParser.java, src/main/java/parser/RemindParser.java, src/main/java/parser/ScheduleParser.java, src/main/java/parser/TodoWithDurationParser.java, src/main/java/parser/TodoWithinPeriodParser.java
implemented logging for exception errors in parser.
For task #101
=> Logging implemented

src/test/java/DeadlineTest.java, src/test/java/EventTest.java
Basic event Junit tests.
Basics as in bare basics.
=> B event basic junit

src/main/java/chronologer/parser/EditParser.java, src/test/java/EditCommandTest.java, src/test/java/EventTest.java, src/test/java/PriorityCommandTest.java
Added Junit Test for EditCommand and PriorityCommand.
=> B more junit tests

build.gradle, src/main/java/chronologer/ChronologerMain.java, src/main/java/chronologer/command/PostponeCommand.java, src/main/java/chronologer/storage/ChronologerStateList.java
Work around to update GUI for postpone was missing, added it in,
=> Updated work around issue with Postpone command.

build.gradle, src/main/java/chronologer/ChronologerMain.java, src/main/java/chronologer/storage/Storage.java, src/main/java/chronologer/storage/TaskListAdapter.java, src/main/java/chronologer/task/Deadline.java, src/main/java/chronologer/task/Event.java, src/main/java/chronologer/task/Task.java, src/main/java/chronologer/task/Todo.java
Now file is human readable.
Added String type to Task class as an identifier for task type which forms a pivot for Json to identify
the subclass.
Added TaskAdapter class to Storage as a JsonParser of sorts since Gson has trouble reading abstract classes.
Do test and ensure properties still the same after load.
(Remove your old arraylist file before you start the program after merge).
=> Implement Json storage via Gson library.

src/main/java/chronologer/command/Command.java, src/main/java/chronologer/command/ExitCommand.java, src/main/java/chronologer/command/ExportCommand.java, src/main/java/chronologer/command/PostponeCommand.java, src/main/java/chronologer/parser/ExportParser.java, src/main/java/chronologer/parser/ParserFactory.java, src/main/java/chronologer/parser/PostponeParser.java, src/main/java/chronologer/storage/CalendarOutput.java, src/main/java/chronologer/task/TaskList.java
Refactor postpone command to be more human readable.
=> B refactor postpone

src/main/java/chronologer/command/AddCommand.java, src/main/java/chronologer/command/AddRecurringCommand.java, src/main/java/chronologer/parser/DateTimeExtractor.java, src/main/java/chronologer/parser/DescriptionParser.java, src/main/java/chronologer/parser/EventParser.java, src/main/java/chronologer/parser/LastDay.java, src/main/java/chronologer/parser/ParserFactory.java, src/main/java/chronologer/parser/RecurringEventParser.java, src/main/java/chronologer/task/Event.java, src/test/java/AddRecurringTest.java
implemented adding of recurring tasks for lectures and tutorials for #108
=> implemented recurring tasks 

src/main/java/chronologer/command/PostponeCommand.java, src/main/java/chronologer/exception/ChronologerException.java, src/test/java/PostponeTest.java
Now postpone command will check if new dates earlier than old dates.
=> Fixed postpone bug in which user can postpone to later dates.

src/main/java/chronologer/command/HelpCommand.java, src/main/java/chronologer/command/ManualCommand.java, src/main/java/chronologer/parser/ParserFactory.java, src/main/java/chronologer/ui/ChatbotWindow.java, src/main/java/chronologer/ui/UiTemporary.java
Check it out! pretty cool to be honest try "help" and "manual".
=> added a help and guide feature for the user!

src/main/java/chronologer/command/CommentCommand.java, src/main/java/chronologer/command/LocationCommand.java, src/main/java/chronologer/task/Deadline.java, src/main/java/chronologer/task/Event.java, src/main/java/chronologer/task/Task.java, src/main/java/chronologer/task/Todo.java, src/test/java/StorageTest.java
Fixed the bug mentioned in #146 and tweaked the confirmation message of comment command
=> Fixed location not showing bug

src/main/java/chronologer/ui/UiTemporary.java
=> added own commands to manual

src/main/java/chronologer/command/ExportCommand.java, src/test/java/ExportTest.java
Added Junit test for export.
Fixed export filename space issue and added priority components.
=> B export junit

src/main/java/chronologer/TaskScheduler.java, src/main/java/chronologer/command/TaskScheduleCommand.java, src/test/java/TaskScheduleTest.java, src/test/java/TaskSchedulerTest.java
Additionally, future-proofed the TaskSchedule test
=> Refactored SLAP to TaskScheduler and TaskSchedule command

src/main/java/chronologer/command/Command.java, src/main/java/chronologer/command/ExportCommand.java, src/main/java/chronologer/exception/ChronologerException.java, src/main/java/chronologer/parser/Parser.java, src/main/java/chronologer/storage/CalendarOutput.java, src/main/java/chronologer/storage/Storage.java, src/main/java/chronologer/storage/TaskListAdapter.java
Implemented logger for storage.
Fix error when exporting ics without anything in it.
=> B storage logger+bug fix

src/main/java/chronologer/command/AddRecurringCommand.java, src/main/java/chronologer/command/Command.java, src/main/java/chronologer/command/CommentCommand.java, src/main/java/chronologer/command/ManualCommand.java, src/main/java/chronologer/command/SearchCommand.java, src/main/java/chronologer/command/TaskScheduleCommand.java, src/main/java/chronologer/exception/MyLogger.java, src/main/java/chronologer/parser/DescriptionParser.java, src/main/java/chronologer/parser/LastDay.java, src/main/java/chronologer/parser/Parser.java, src/main/java/chronologer/parser/RecurringEventParser.java, src/main/java/chronologer/parser/SearchParser.java, src/main/java/chronologer/task/Deadline.java, src/main/java/chronologer/task/Event.java, src/main/java/chronologer/task/Todo.java, src/test/java/AddRecurringTest.java
for #181 
additionally added reposense tags
=> implemented logging for command classes

src/main/java/chronologer/command/AddCommand.java, src/main/java/chronologer/command/ExportCommand.java, src/main/java/chronologer/command/PostponeCommand.java, src/main/java/chronologer/parser/CommentParser.java, src/main/java/chronologer/parser/DeadlineParser.java, src/main/java/chronologer/parser/DeleteParser.java, src/main/java/chronologer/parser/DoneParser.java, src/main/java/chronologer/parser/EditParser.java, src/main/java/chronologer/parser/EventParser.java, src/main/java/chronologer/parser/FindParser.java, src/main/java/chronologer/parser/IgnoreParser.java, src/main/java/chronologer/parser/LocationParser.java, src/main/java/chronologer/parser/PostponeParser.java, src/main/java/chronologer/parser/PriorityParser.java, src/main/java/chronologer/parser/RemindParser.java, src/main/java/chronologer/parser/TodoParser.java, src/main/java/chronologer/parser/ViewParser.java, src/main/java/chronologer/storage/Storage.java, src/main/java/chronologer/storage/TaskListAdapter.java
Bunch of refactoring.
Added comments to methods without them.
Apply SLAP principle to methods with varying abstraction levels.
Changed some parser constructors to package private as indicated by IntelliJ.
=> Added comments to methods and applied some SLAP.

src/main/java/chronologer/exception/ChronologerException.java, src/main/java/chronologer/parser/DescriptionParser.java, src/main/java/chronologer/parser/LastDay.java, src/main/java/chronologer/parser/RecurringEventParser.java
error fix for recurring tasks addition due to modcode extractor returning  a null value
=> error fix 

.gitignore, src/main/java/chronologer/command/ThemeCommand.java, src/main/java/chronologer/command/ViewCommand.java, src/main/java/chronologer/command/WeekCommand.java, src/main/java/chronologer/exception/ChronologerException.java, src/main/java/chronologer/parser/DeadlineParser.java, src/main/java/chronologer/parser/DescriptionParser.java, src/main/java/chronologer/parser/EventParser.java, src/main/java/chronologer/parser/IndexParser.java, src/main/java/chronologer/parser/LastDay.java, src/main/java/chronologer/parser/LocationParser.java, src/main/java/chronologer/parser/Parser.java, src/main/java/chronologer/parser/ParserFactory.java, src/main/java/chronologer/parser/PostponeParser.java, src/main/java/chronologer/parser/PriorityParser.java, src/main/java/chronologer/parser/RecurringEventParser.java, src/main/java/chronologer/parser/RemindParser.java, src/main/java/chronologer/parser/ScheduleParser.java, src/main/java/chronologer/parser/TodoWithDurationParser.java, src/main/java/chronologer/parser/TodoWithinPeriodParser.java, src/main/java/chronologer/storage/CalendarOutput.java, src/main/java/chronologer/storage/ChronologerStateList.java, src/main/java/chronologer/storage/Storage.java, src/main/java/chronologer/task/TaskList.java, src/main/java/chronologer/ui/ChatbotWindow.java, src/main/java/chronologer/ui/UiMessageHandler.java, src/main/resources/view/DialogBox.fxml
Completed removing of all unnecessary writes to UiMessageHandler.
=> Standardized comments and removed remaining redundant writes.

src/main/java/chronologer/parser/ParserFactory.java
changed the parserfactory to lowercase the command string as it pass through
=> change command to lowercase

src/main/java/chronologer/command/Command.java, src/main/java/chronologer/command/ExportCommand.java, src/main/java/chronologer/parser/DeadlineParser.java, src/main/java/chronologer/parser/EventParser.java, src/main/java/chronologer/parser/Flag.java, src/main/java/chronologer/parser/LastDay.java, src/main/java/chronologer/parser/Parser.java, src/main/java/chronologer/parser/ParserFactory.java, src/main/java/chronologer/storage/CalendarOutput.java, src/main/java/chronologer/storage/Storage.java, src/main/java/chronologer/ui/DialogBox.java
tried my best to convert strings i caught for #188
=> changed magic strings to constants

src/main/java/chronologer/exception/ChronologerException.java, src/main/java/chronologer/parser/DescriptionParser.java, src/main/java/chronologer/parser/EventParser.java, src/test/java/EditCommandTest.java, src/test/java/ExportTest.java, src/test/java/PriorityCommandTest.java, src/test/java/chronologer/parser/EditParserTest.java, src/test/java/chronologer/parser/PriorityParserTest.java
Added tests for edit and priority parser.
=> B parser test
